/**:
  ros__parameters:
    camera_name: "stereo_right"
    frame_id: "stereo_right_optical"
    camera_info_url: ""
    image_encoding: "rgb8"
    use_sensor_data_qos: false
    sync_sink: false
    use_gst_timestamps: true
    autostart: true
    calib_mode: true
    gscam_config: >
      libcamerasrc camera-name="/base/axi/pcie@1000120000/rp1/i2c@88000/imx219@10" !
      queue leaky=downstream max-size-buffers=1 !
      video/x-raw,format=NV12,width=1640,height=1232,framerate=5/1 !
      videoflip method="rotate-180" !
      videoconvert n-threads=4 !
      video/x-raw,format=RGB