controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    arm_forward_controller:
      type: forward_command_controller/ForwardCommandController
    omni_base_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController
    lekiwi_imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
    lekiwi_magnetometer_broadcaster:
      type: magnetometer_broadcaster/MagnetometerBroadcaster

arm_trajectory_controller:
  ros__parameters:
    joints:
      - arm_shoulder_pan
      - arm_shoulder_lift
      - arm_elbow_flex
      - arm_wrist_flex
      - arm_wrist_roll
      - arm_gripper
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    open_loop_control: true
    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: false
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

arm_forward_controller:
  ros__parameters:
    joints:
      - arm_shoulder_pan
      - arm_shoulder_lift
      - arm_elbow_flex
      - arm_wrist_flex
      - arm_wrist_roll
      - arm_gripper
    interface_name: position

omni_base_controller:
  ros__parameters:
    wheel_names: [base_right_wheel, base_left_wheel, base_back_wheel]
    wheel_offset: 2.0943951024
    robot_radius: 0.1268
    wheel_radius: 0.065 
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: true
    open_loop: false
    position_feedback: false
    cmd_vel_timeout: 0.25
    diagonal_covariance:
      pose: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

lekiwi_imu_broadcaster:
  ros__parameters:
    sensor_name: icm20948_imu
    frame_id: icm20948_imu
    static_covariance_orientation: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    static_covariance_angular_velocity: [0.00005, 0.0, 0.0, 0.0, 0.00005, 0.0, 0.0, 0.0, 0.00005]
    static_covariance_linear_acceleration: [0.0004, 0.0, 0.0, 0.0, 0.0004, 0.0, 0.0, 0.0, 0.0004]

lekiwi_magnetometer_broadcaster:
  ros__parameters:
    sensor_name: icm20948_imu
    frame_id: icm20948_imu
    static_covariance: [0.001, 0.0, 0.0, 0.0, 0.001, 0.0, 0.0, 0.0, 0.001]
