# Request
geometry_msgs/Point target_point
string target_frame
float64 required_pitch_angle
bool compute_suggested_pose
---
# Response
bool reachable
float64 distance_to_target
sensor_msgs/JointState ik_solution
geometry_msgs/PoseStamped suggested_base_pose
string message

