# ================= Request =================
# High-level UCI Chess Move
string uci_move
bool is_capture

---
# ================= Response =================
# Kiểu kế hoạch thực thi cho Task Orchestrator
uint8 PLAN_ZERO_NAV    = 0   # Robot đứng yên, tay gắp đặt luôn
uint8 PLAN_SINGLE_BASE = 1   # 1 lần Nav2 tới vị trí chung (hoặc gắp ăn quân)
uint8 PLAN_DUAL_BASE   = 2   # Cần 2 lần Nav2: B_pick -> Pick -> B_place -> Place

uint8 plan_type
bool feasible

# Pose đế robot cần di chuyển tới
geometry_msgs/PoseStamped pick_base_pose
geometry_msgs/PoseStamped place_base_pose   # Bằng pick_base_pose nếu ZERO_NAV hoặc SINGLE_BASE

string message


