mock_policy_server:
  ros__parameters:
    phase_duration_sec: 0.6
    simulate_delay: true
    action_name: "/manipulation/execute_chess_move"

cartesian_service_node:
  ros__parameters:
    action_server_name: "/arm_trajectory_controller/follow_joint_trajectory"
    joint_states_topic: "/joint_states"
    default_duration_sec: 2.5
    sampling_rate_hz: 50.0

manipulation_action_server:
  ros__parameters:
    action_name: "/manipulation/execute_chess_move"
    trajectory_controller_action: "/arm_trajectory_controller/follow_joint_trajectory"
    joint_states_topic: "/joint_states"
    phase_duration_sec: 1.2
    sampling_rate_hz: 50.0
