#!/usr/bin/env python3
# Copyright 2026 LeKiwi Labs
# Licensed under the Apache License, Version 2.0.

from lekiwi_orchestrator.chess_mission_orchestrator import main

if __name__ == "__main__":
    main()
