/**:
  ros__parameters:
    camera_info_url: ""
    use_sensor_data_qos: true
    sync_sink: false
    use_gst_timestamps: true
    image_encoding: "rgb8"

/cameras/stereo_left/gscam:
  ros__parameters:
    camera_info_url: package://lekiwi_bringup/config/perception/camera_info/stereo_left.yaml
    frame_id: "stereo_left_optical"
    camera_name: "stereo_left"
    active_modes: [1, 2]
    gscam_config: >
      libcamerasrc camera-name="/base/axi/pcie@1000120000/rp1/i2c@80000/imx219@10" ! 
      valve name=gate drop=true ! 
      queue leaky=downstream max-size-buffers=1 ! 
      video/x-raw,format=NV12,width=3280,height=2464,framerate=20/1 ! 
      videoscale add-borders=true n-threads=4 ! \
      video/x-raw,format=NV12,width=640,height=640,pixel-aspect-ratio=1/1 ! 
      videoflip method="rotate-180" ! 
      videoconvert n-threads=4 ! 
      video/x-raw,format=RGB
/cameras/stereo_right/gscam:
  ros__parameters:
    camera_info_url: package://lekiwi_bringup/config/perception/camera_info/stereo_right.yaml
    frame_id: "stereo_right_optical"
    camera_name: "stereo_right"
    active_modes: [3]
    gscam_config: >
      libcamerasrc camera-name="/base/axi/pcie@1000120000/rp1/i2c@88000/imx219@10" !
      valve name=gate drop=true !
      queue leaky=downstream max-size-buffers=1 !
      video/x-raw,format=NV12,width=1640,height=1232,framerate=25/1 !
      videocrop left=204 right=204 !
      videoscale n-threads=4 !
      video/x-raw,format=NV12,width=384,height=384,pixel-aspect-ratio=1/1 !
      videoflip method="rotate-180" !
      videoconvert n-threads=4 !
      video/x-raw,format=RGB


/cameras/usb_wrist/gscam:
  ros__parameters:
    camera_info_url: package://lekiwi_bringup/config/perception/camera_info/usb_wrist.yaml
    frame_id: "wrist_camera_optical"
    camera_name: "usb_wrist"
    active_modes: [3]
    gscam_config: >
      v4l2src device=/dev/usb_wrist io-mode=mmap extra-controls="c,power_line_frequency=1,sharpness=256,contrast=356" !
      valve name=gate drop=true !
      image/jpeg,width=1280,height=720,framerate=25/1 !
      queue leaky=downstream max-size-buffers=1 !
      jpegdec !
      video/x-raw,format=I420 !
      videocrop left=280 right=280 !
      videoscale n-threads=4 !
      video/x-raw,format=I420,width=384,height=384,pixel-aspect-ratio=1/1 !
      videobalance contrast=1.2 brightness=-0.2 !
      videoconvert n-threads=4 !
      video/x-raw,format=RGB

/cameras/usb_side/gscam:
  ros__parameters:
    camera_info_url: package://lekiwi_bringup/config/perception/camera_info/usb_side.yaml
    frame_id: "side_camera_optical"
    camera_name: "usb_side"
    active_modes: [3]
    gscam_config: >
      v4l2src device=/dev/usb_side io-mode=mmap extra-controls="c,auto_exposure=1,exposure_time_absolute=200,gain=30,brightness=20,contrast=20,sharpness=10000" !
      valve name=gate drop=true !
      image/jpeg,width=1280,height=720,framerate=30/1 !
      videorate drop-only=true !
      image/jpeg,framerate=25/1 !
      queue leaky=downstream max-size-buffers=1 !
      jpegdec !
      video/x-raw,format=I420 !
      videocrop left=280 right=280 !
      videoscale n-threads=4 !
      video/x-raw,format=I420,width=384,height=384,pixel-aspect-ratio=1/1 !
      videoflip method="counterclockwise" !
      videoconvert n-threads=4 !
      video/x-raw,format=RGB !
    # videomedian filtersize=5 lum-only=true !
    # gamma gamma=1.8 !
    # videobalance contrast=0.9 !
    # videobalance brightness=-0.05 !
 