# Copyright 2026 LeKiwi Labs
# Licensed under the Apache License, Version 2.0.

"""Unit tests for manual observation calibrator helper functions and kinematics."""

import math
import os
import tempfile
import yaml
import pytest

from lekiwi_calibration.observation.manual_obs_calibrator_node import (
    compute_azimuth_angle,
    compute_orbit_velocity,
    format_observation_yaml,
    normalize_angle,
)


def test_normalize_angle() -> None:
    assert math.isclose(normalize_angle(0.0), 0.0, abs_tol=1e-5)
    assert math.isclose(normalize_angle(math.pi), math.pi, abs_tol=1e-5)
    assert math.isclose(normalize_angle(3.0 * math.pi), math.pi, abs_tol=1e-5)
    assert math.isclose(normalize_angle(-3.0 * math.pi), -math.pi, abs_tol=1e-5)
    assert math.isclose(normalize_angle(math.pi / 2.0), math.pi / 2.0, abs_tol=1e-5)


def test_compute_azimuth_angle() -> None:
    # +X axis -> 0 rad
    assert math.isclose(compute_azimuth_angle(1.0, 0.0), 0.0, abs_tol=1e-5)
    # +Y axis -> +pi/2 rad
    assert math.isclose(compute_azimuth_angle(0.0, 1.0), math.pi / 2.0, abs_tol=1e-5)
    # -X axis -> pi rad
    assert math.isclose(compute_azimuth_angle(-1.0, 0.0), math.pi, abs_tol=1e-5)
    # -Y axis -> -pi/2 rad
    assert math.isclose(compute_azimuth_angle(0.0, -1.0), -math.pi / 2.0, abs_tol=1e-5)
    # Quadrant 1 (45 deg)
    assert math.isclose(compute_azimuth_angle(1.0, 1.0), math.pi / 4.0, abs_tol=1e-5)
    # Quadrant 4 (-45 deg)
    assert math.isclose(compute_azimuth_angle(1.0, -1.0), -math.pi / 4.0, abs_tol=1e-5)


def test_compute_orbit_velocity_stop() -> None:
    vx, vy, wz = compute_orbit_velocity(
        r_curr=0.56,
        theta_curr=-math.pi / 2.0,
        psi_curr=math.pi / 2.0,
        orbit_dir=0,
        r_target=0.56,
    )
    assert vx == 0.0
    assert vy == 0.0
    assert wz == 0.0


def test_compute_orbit_velocity_ccw_and_cw() -> None:
    # Robot at south (0, -0.56), theta = -pi/2, facing north (psi = pi/2)
    r_target = 0.56
    v_orbit = 0.08

    # Case 1: Exactly at target radius, CCW (+1)
    vx_ccw, vy_ccw, wz_ccw = compute_orbit_velocity(
        r_curr=r_target,
        theta_curr=-math.pi / 2.0,
        psi_curr=math.pi / 2.0,  # facing north toward center
        orbit_dir=1,
        r_target=r_target,
        v_orbit=v_orbit,
    )
    assert math.isclose(vx_ccw, 0.0, abs_tol=1e-5)  # no radial correction needed
    assert math.isclose(vy_ccw, v_orbit, abs_tol=1e-5)
    # wz should have positive feedforward vy / r
    assert wz_ccw > 0.0

    # Case 2: CW (-1)
    vx_cw, vy_cw, wz_cw = compute_orbit_velocity(
        r_curr=r_target,
        theta_curr=-math.pi / 2.0,
        psi_curr=math.pi / 2.0,
        orbit_dir=-1,
        r_target=r_target,
        v_orbit=v_orbit,
    )
    assert math.isclose(vy_cw, -v_orbit, abs_tol=1e-5)
    assert wz_cw < 0.0

    # Case 3: Robot too far (r_curr = 0.70m > 0.56m) -> vx should be positive to approach center
    vx_far, _, _ = compute_orbit_velocity(
        r_curr=0.70,
        theta_curr=-math.pi / 2.0,
        psi_curr=math.pi / 2.0,
        orbit_dir=1,
        r_target=r_target,
    )
    assert vx_far > 0.0

    # Case 4: Robot too close (r_curr = 0.40m < 0.56m) -> vx should be negative to back away
    vx_close, _, _ = compute_orbit_velocity(
        r_curr=0.40,
        theta_curr=-math.pi / 2.0,
        psi_curr=math.pi / 2.0,
        orbit_dir=1,
        r_target=r_target,
    )
    assert vx_close < 0.0


def test_yaml_export_merging() -> None:
    # Step 1: Format relocalize mode
    content_step1 = format_observation_yaml(
        existing_data={},
        calib_mode="relocalize",
        samples_count=3,
        avg_r=0.563,
        sorted_offsets=[-0.314, 0.0, 0.314],
    )

    assert "# Auto-generated by LeKiwi Manual Observation Calibrator" in content_step1
    assert "# Mode: relocalize | Samples: 3" in content_step1
    assert "standoff_distance: 0.563   # Bán kính trung bình thực tế đo được từ các điểm chọn" in content_step1
    assert "relocalize: [-0.314, 0.000, 0.314]" in content_step1

    # Step 2: Merge post_move_verify into existing data
    loaded_step1 = yaml.safe_load(content_step1)
    content_step2 = format_observation_yaml(
        existing_data=loaded_step1,
        calib_mode="post_move_verify",
        samples_count=5,
        avg_r=0.565,
        sorted_offsets=[-0.558, -0.314, 0.0, 0.314, 0.558],
    )

    # Validate that both modes exist and are preserved
    assert "# Mode: post_move_verify | Samples: 5" in content_step2
    assert "standoff_distance: 0.565   # Bán kính trung bình thực tế đo được từ các điểm chọn" in content_step2
    assert "relocalize: [-0.314, 0.000, 0.314]" in content_step2
    assert "post_move_verify: [-0.558, -0.314, 0.000, 0.314, 0.558]" in content_step2

    # Validate valid YAML syntax
    final_dict = yaml.safe_load(content_step2)
    assert final_dict["observation"]["standoff_distance"] == 0.565
    assert len(final_dict["observation"]["angle_offsets"]["relocalize"]) == 3
    assert len(final_dict["observation"]["angle_offsets"]["post_move_verify"]) == 5
