# Copyright 2026 LeKiwi Labs
# Licensed under the Apache License, Version 2.0.

"""
Manual Observation Viewpoint & Standoff Calibrator Node.

Enables human-in-the-loop observation calibration for LeKiwi:
1. Automatically gates camera stream by publishing to latched /perception_context.
2. Supports circular orbit teleoperation (D-Pad Left/Right) keeping robot camera aimed at board center.
3. Records viewpoints (D-Pad Up: Save, D-Pad Down: Discard).
4. Exports calibrated standoff distance and angle offsets to independent YAML configuration.
"""

from __future__ import annotations

import math
import os
import sys
from datetime import datetime
from typing import List, Optional, Tuple
import yaml

import rclpy
from rclpy.node import Node
from rclpy.qos import DurabilityPolicy, HistoryPolicy, QoSProfile, ReliabilityPolicy
import tf2_ros
from geometry_msgs.msg import TransformStamped, TwistStamped
from sensor_msgs.msg import Joy
from std_srvs.srv import Trigger

from lekiwi_interfaces.msg import PerceptionContext


def normalize_angle(angle: float) -> float:
    """Normalize angle to range [-pi, pi]."""
    return math.atan2(math.sin(angle), math.cos(angle))


def compute_azimuth_angle(rx: float, ry: float) -> float:
    """Compute polar azimuth angle in [-pi, pi] relative to +X axis of chessboard/map."""
    return math.atan2(ry, rx)


def compute_orbit_velocity(
    r_curr: float,
    theta_curr: float,
    psi_curr: float,
    orbit_dir: int,
    r_target: float,
    v_orbit: float = 0.08,
    k_radial: float = 1.2,
    k_yaw: float = 1.5,
    max_vx: float = 0.05,
    max_wz: float = 0.35,
) -> Tuple[float, float, float]:
    """
    Calculate closed-loop omni base velocities for circular orbit around board center.

    :param r_curr: Current distance to board center (m).
    :param theta_curr: Current polar azimuth in board frame (rad).
    :param psi_curr: Current robot heading in board frame (rad).
    :param orbit_dir: Direction (+1 for CCW, -1 for CW, 0 for stop).
    :param r_target: Target standoff distance (m).
    :param v_orbit: Nominal tangential velocity (m/s).
    :param k_radial: Proportional gain for radial distance error.
    :param k_yaw: Proportional gain for heading error toward center.
    :param max_vx: Maximum linear radial velocity clamp (m/s).
    :param max_wz: Maximum angular velocity clamp (rad/s).
    :return: (v_x, v_y, w_z) in robot base_footprint frame.
    """
    if orbit_dir == 0:
        return 0.0, 0.0, 0.0

    # Facing board center requires heading along vector (-x, -y) from robot
    psi_target = normalize_angle(theta_curr + math.pi)
    e_psi = normalize_angle(psi_target - psi_curr)

    # Robot base: +x is forward (toward center when oriented inward).
    # If r_curr > r_target, robot is too far, needs positive +vx to move inward.
    v_x_raw = k_radial * (r_curr - r_target)
    v_x = max(-max_vx, min(max_vx, v_x_raw))

    # +y is robot left. Moving CCW around center means moving to robot's left (+vy).
    v_y = float(orbit_dir) * v_orbit

    # Angular velocity: Feedforward (tangent speed / radius) + Feedback heading P-term
    effective_r = max(r_curr, 0.1)
    w_z_raw = (v_y / effective_r) + (k_yaw * e_psi)
    w_z = max(-max_wz, min(max_wz, w_z_raw))

    return v_x, v_y, w_z


def format_observation_yaml(
    existing_data: dict,
    calib_mode: str,
    samples_count: int,
    avg_r: float,
    sorted_offsets: List[float],
) -> str:
    """Format observation YAML preserving existing modes and custom comments."""
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    obs_dict = existing_data.setdefault("observation", {})
    obs_dict["standoff_distance"] = round(avg_r, 3)
    angle_offsets_dict = obs_dict.setdefault("angle_offsets", {})
    angle_offsets_dict[calib_mode] = sorted_offsets

    lines = [
        "# Auto-generated by LeKiwi Manual Observation Calibrator",
        f"# Calibrated at: {now_str}",
        f"# Mode: {calib_mode} | Samples: {samples_count}",
        "",
        "observation:",
        f"  standoff_distance: {obs_dict['standoff_distance']:.3f}   # Bán kính trung bình thực tế đo được từ các điểm chọn",
        "  angle_offsets:",
    ]

    # Preserve order: relocalize first if exists, then post_move_verify, then others
    keys = list(angle_offsets_dict.keys())
    preferred_order = ["relocalize", "post_move_verify"]
    sorted_keys = [k for k in preferred_order if k in keys] + [
        k for k in keys if k not in preferred_order
    ]

    for k in sorted_keys:
        vals = angle_offsets_dict[k]
        val_strs = [f"{v:.3f}" if isinstance(v, float) else str(v) for v in vals]
        lines.append(f"    {k}: [{', '.join(val_strs)}]")

    # Append any extra fields under observation
    for k, v in obs_dict.items():
        if k not in ("standoff_distance", "angle_offsets"):
            lines.append(f"  {k}: {v}")

    # Append any top-level keys outside observation
    for k, v in existing_data.items():
        if k != "observation":
            extra_yaml = yaml.dump({k: v}, default_flow_style=False).strip()
            lines.append("")
            lines.append(extra_yaml)

    lines.append("")
    return "\n".join(lines)


class ManualObsCalibratorNode(Node):
    """Interactive Gamepad Calibration Node for Standoff Distance and Observation Offsets."""

    def __init__(self) -> None:
        super().__init__("manual_obs_calibrator")

        # Declare parameters
        self.declare_parameter("calib_mode", "relocalize")
        self.declare_parameter("target_standoff_distance", 0.56)
        self.declare_parameter("orbit_linear_speed", 0.08)
        self.declare_parameter("radial_kp", 1.2)
        self.declare_parameter("yaw_kp", 1.5)
        self.declare_parameter("board_frame", "chessboard_frame")
        self.declare_parameter("base_frame", "base_footprint")
        self.declare_parameter(
            "output_yaml",
            "/root/docker_ws/lekiwi_ros2/lekiwi_calibration/config/observation_angle_offsets.yaml",
        )

        self.calib_mode = str(self.get_parameter("calib_mode").value).strip().lower()
        self.r_target = float(self.get_parameter("target_standoff_distance").value)
        self.v_orbit = float(self.get_parameter("orbit_linear_speed").value)
        self.k_radial = float(self.get_parameter("radial_kp").value)
        self.k_yaw = float(self.get_parameter("yaw_kp").value)
        self.board_frame = str(self.get_parameter("board_frame").value)
        self.base_frame = str(self.get_parameter("base_frame").value)
        self.output_yaml = str(self.get_parameter("output_yaml").value)

        # Latched /perception_context publisher (Durability: TRANSIENT_LOCAL)
        latched_qos = QoSProfile(
            history=HistoryPolicy.KEEP_LAST,
            depth=1,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
        )
        self.context_pub = self.create_publisher(
            PerceptionContext, "/perception_context", latched_qos
        )
        self._publish_perception_context()

        # Command velocity publisher for calibration (priority 200 in twist_mux)
        self.cmd_vel_pub = self.create_publisher(TwistStamped, "/cmd_vel_calib", 10)

        # TF2 listener
        self.tf_buffer = tf2_ros.Buffer()
        self.tf_listener = tf2_ros.TransformListener(self.tf_buffer, self)

        # Joy input handling and edge detection state
        self.prev_dpad_y = 0.0
        self.active_orbit_dir = 0  # +1: CCW (Left), -1: CW (Right), 0: Stop
        self.joy_sub = self.create_subscription(Joy, "/joy", self.handle_joy, 10)

        # Recorded sample buffer: List of (r_meters, delta_theta_rad)
        self.recorded_samples: List[Tuple[float, float]] = []

        # Service for saving calibration results
        self.save_srv = self.create_service(
            Trigger, "~/save_to_yaml", self.handle_save_service
        )

        # Control loop timer (20 Hz)
        self.control_timer = self.create_timer(0.05, self.control_loop)

        self.get_logger().info(
            f"ManualObsCalibratorNode initialized.\n"
            f"  - Mode: {self.calib_mode}\n"
            f"  - Target Standoff: {self.r_target:.3f} m\n"
            f"  - Angle Zero Reference: +X axis of '{self.board_frame}'\n"
            f"  - Output YAML: {self.output_yaml}"
        )

    def _publish_perception_context(self) -> None:
        """Publish latched perception context matching active calibration mode."""
        msg = PerceptionContext()
        if self.calib_mode == "relocalize":
            msg.value = PerceptionContext.TF_TRACKING_AND_NAV  # 1
            self.get_logger().info(
                "[PERCEPTION] Mode 'relocalize' -> Published TF_TRACKING_AND_NAV (1)"
            )
        elif self.calib_mode == "post_move_verify":
            msg.value = PerceptionContext.BOARD_STATE_SCAN  # 2
            self.get_logger().info(
                "[PERCEPTION] Mode 'post_move_verify' -> Published BOARD_STATE_SCAN (2)"
            )
        else:
            self.get_logger().warn(
                f"[PERCEPTION] Unknown calib_mode '{self.calib_mode}'. Fallback to TF_TRACKING_AND_NAV."
            )
            msg.value = PerceptionContext.TF_TRACKING_AND_NAV
        self.context_pub.publish(msg)

    def handle_joy(self, msg: Joy) -> None:
        """
        Process gamepad inputs:
        - D-Pad Left/Right (axis 6): Continuous hold for CCW/CW circular orbit.
        - D-Pad Up/Down (axis 7): Edge-triggered Save/Discard.
        """
        dpad_x = msg.axes[6] if len(msg.axes) > 6 else 0.0
        dpad_y = msg.axes[7] if len(msg.axes) > 7 else 0.0

        # D-Pad Left (> 0.5) -> CCW (+1) | D-Pad Right (< -0.5) -> CW (-1)
        if dpad_x > 0.5:
            self.active_orbit_dir = 1
        elif dpad_x < -0.5:
            self.active_orbit_dir = -1
        else:
            if self.active_orbit_dir != 0:
                # Stop instantly on button release
                self._stop_motion()
            self.active_orbit_dir = 0

        # Edge detection for D-Pad Up (Save)
        if dpad_y > 0.5 and self.prev_dpad_y <= 0.5:
            self.capture_sample()
        # Edge detection for D-Pad Down (Discard)
        elif dpad_y < -0.5 and self.prev_dpad_y >= -0.5:
            self.discard_sample()

        self.prev_dpad_y = dpad_y

    def _stop_motion(self) -> None:
        """Publish zero velocity to immediately stop circular orbit."""
        stop_cmd = TwistStamped()
        stop_cmd.header.stamp = self.get_clock().now().to_msg()
        stop_cmd.header.frame_id = self.base_frame
        self.cmd_vel_pub.publish(stop_cmd)

    def control_loop(self) -> None:
        """Periodic control loop calculating closed-loop circular orbit velocity."""
        if self.active_orbit_dir == 0:
            return

        try:
            t = self.tf_buffer.lookup_transform(
                self.board_frame, self.base_frame, rclpy.time.Time()
            )
        except Exception as ex:
            self.get_logger().warn(
                f"TF lookup '{self.board_frame}' -> '{self.base_frame}' failed: {ex}",
                throttle_duration_sec=2.0,
            )
            return

        rx = float(t.transform.translation.x)
        ry = float(t.transform.translation.y)
        r_curr = math.hypot(rx, ry)
        theta_curr = math.atan2(ry, rx)

        # Extract yaw from quaternion
        q = t.transform.rotation
        siny_cosp = 2.0 * (q.w * q.z + q.x * q.y)
        cosy_cosp = 1.0 - 2.0 * (q.y * q.y + q.z * q.z)
        psi_curr = math.atan2(siny_cosp, cosy_cosp)

        vx, vy, wz = compute_orbit_velocity(
            r_curr=r_curr,
            theta_curr=theta_curr,
            psi_curr=psi_curr,
            orbit_dir=self.active_orbit_dir,
            r_target=self.r_target,
            v_orbit=self.v_orbit,
            k_radial=self.k_radial,
            k_yaw=self.k_yaw,
        )

        cmd = TwistStamped()
        cmd.header.stamp = self.get_clock().now().to_msg()
        cmd.header.frame_id = self.base_frame
        cmd.twist.linear.x = vx
        cmd.twist.linear.y = vy
        cmd.twist.angular.z = wz
        self.cmd_vel_pub.publish(cmd)

    def capture_sample(self) -> None:
        """Record current robot viewpoint pose relative to chessboard_frame."""
        try:
            t = self.tf_buffer.lookup_transform(
                self.board_frame, self.base_frame, rclpy.time.Time()
            )
            rx = float(t.transform.translation.x)
            ry = float(t.transform.translation.y)
            r_curr = math.hypot(rx, ry)
            theta_curr = compute_azimuth_angle(rx, ry)

            self.recorded_samples.append((r_curr, theta_curr))
            self.get_logger().info(
                f"[SAMPLE #{len(self.recorded_samples)} SAVED] Mode: {self.calib_mode} | "
                f"R: {r_curr:.3f}m | Azimuth (+X ref): {theta_curr:+.3f} rad ({math.degrees(theta_curr):+.1f}°)"
            )
        except Exception as ex:
            self.get_logger().error(f"Failed to capture viewpoint sample: {ex}")

    def discard_sample(self) -> None:
        """Remove last recorded sample."""
        if self.recorded_samples:
            removed = self.recorded_samples.pop()
            self.get_logger().warn(
                f"[SAMPLE DISCARDED] Removed R={removed[0]:.3f}m, "
                f"Offset={removed[1]:+.3f} rad. Remaining samples: {len(self.recorded_samples)}"
            )
        else:
            self.get_logger().warn("[SAMPLE DISCARD] Sample buffer is empty.")

    def handle_save_service(
        self, request: Trigger.Request, response: Trigger.Response
    ) -> Trigger.Response:
        """Compute final metrics and safely export to independent YAML file."""
        if not self.recorded_samples:
            response.success = False
            response.message = f"No samples collected for mode '{self.calib_mode}'."
            return response

        avg_r = sum(s[0] for s in self.recorded_samples) / len(self.recorded_samples)
        sorted_offsets = sorted(round(s[1], 3) for s in self.recorded_samples)

        # Read existing YAML to preserve settings for the other mode
        existing_data = {}
        if os.path.exists(self.output_yaml):
            try:
                with open(self.output_yaml, "r", encoding="utf-8") as f:
                    existing_data = yaml.safe_load(f) or {}
            except Exception as ex:
                self.get_logger().warn(
                    f"Could not load existing YAML, creating fresh: {ex}"
                )
                existing_data = {}

        yaml_content = format_observation_yaml(
            existing_data=existing_data,
            calib_mode=self.calib_mode,
            samples_count=len(self.recorded_samples),
            avg_r=avg_r,
            sorted_offsets=sorted_offsets,
        )

        # Ensure target directory exists
        os.makedirs(os.path.dirname(os.path.abspath(self.output_yaml)), exist_ok=True)
        try:
            with open(self.output_yaml, "w", encoding="utf-8") as f:
                f.write(yaml_content)

            response.success = True
            response.message = (
                f"Successfully exported {len(sorted_offsets)} offsets for '{self.calib_mode}' "
                f"(standoff: {avg_r:.3f}m) to {self.output_yaml}"
            )
            self.get_logger().info(f"[EXPORT COMPLETE] {response.message}")
        except Exception as ex:
            response.success = False
            response.message = f"Failed to write YAML file: {ex}"
            self.get_logger().error(response.message)

        return response


def main(args: Optional[List[str]] = None) -> None:
    rclpy.init(args=args)
    node = ManualObsCalibratorNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node._stop_motion()
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
