# Copyright 2026 LeKiwi Labs
# Licensed under the Apache License, Version 2.0.

"""
Interactive Gamepad Calibration Node for Arm Landmark Poses.

Calculates and records landmark arm poses (e.g. home, stow, clear_left, clear_right)
for LeKiwi manipulation_action_server using human-in-the-loop lead-through:
1. Subscribes to /joint_states and /joy.
2. Steps sequentially through configured target poses (target_poses ROS parameter).
3. D-Pad UP: captures current joint positions for active target pose.
4. D-Pad DOWN: undoes/discards the most recent capture.
5. Menu / Start button (or ~/save_to_yaml service): exports calibrated joint positions
   to a manipulation_action_server-compatible YAML configuration.
"""

from __future__ import annotations

from datetime import datetime
import os
from typing import Dict, List, Optional
import yaml

import rclpy
from rclpy.node import Node
from rclpy.qos import DurabilityPolicy, HistoryPolicy, QoSProfile, ReliabilityPolicy
from sensor_msgs.msg import JointState, Joy
from std_srvs.srv import Trigger

# Fallback defaults conforming to SOLID design (resilient fail-safe defaults)
DEFAULT_TARGET_POSES: List[str] = ["home", "stow", "clear_left", "clear_right"]

DEFAULT_ARM_JOINTS: List[str] = [
    "arm_shoulder_pan",
    "arm_shoulder_lift",
    "arm_elbow_flex",
    "arm_wrist_flex",
    "arm_wrist_roll",
    "arm_gripper",
]


def extract_joint_positions(
    msg: JointState, arm_joints: List[str]
) -> List[float]:
    """Safely extract ordered joint positions according to arm_joints specification.

    Conforms to ROS 2 engineering principle: JointState.name defines order,
    never guess or assume fixed index positions (Pitfall 17).

    Args:
        msg: JointState ROS 2 message.
        arm_joints: Explicit list of required joint names.

    Returns:
        List of joint positions matching arm_joints order.

    Raises:
        ValueError: If any required joint is missing from the JointState message.
    """
    name_to_pos: Dict[str, float] = dict(zip(msg.name, msg.position))
    missing = [j for j in arm_joints if j not in name_to_pos]
    if missing:
        raise ValueError(
            f"JointState message missing required joints: {missing}. Present: {msg.name}"
        )
    return [name_to_pos[j] for j in arm_joints]


def format_arm_poses_yaml(
    existing_data: dict,
    calibrated_poses: Dict[str, List[float]],
    arm_joints: List[str],
    target_poses: Optional[List[str]] = None,
    precision: int = 4,
) -> str:
    """Format arm landmark poses into YAML compatible with manipulation_action_server.

    Follows Open/Closed Principle: Can output any sequence of calibrated poses.

    Args:
        existing_data: Existing configuration dictionary to preserve other fields.
        calibrated_poses: Mapping of pose name to ordered joint values.
        arm_joints: List of joint names corresponding to list indices.
        target_poses: Optional ordered list of pose names to structure output.
        precision: Floating-point decimal precision.

    Returns:
        Formatted YAML string ready for writing to disk.
    """
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ordering = target_poses if target_poses is not None else list(calibrated_poses.keys())

    # Update dictionary structure
    server_dict = existing_data.setdefault("manipulation_action_server", {})
    params_dict = server_dict.setdefault("ros__parameters", {})
    named_poses_dict = params_dict.setdefault("named_poses", {})

    for pose_name, values in calibrated_poses.items():
        named_poses_dict[pose_name] = [round(float(v), precision) for v in values]

    lines = [
        "# Auto-generated by LeKiwi Arm Pose Calibrator",
        f"# Calibrated at: {now_str}",
        f"# Arm joint ordering: {arm_joints}",
        "",
        "manipulation_action_server:",
        "  ros__parameters:",
        "    named_poses:",
    ]

    for pose_name in ordering:
        if pose_name in named_poses_dict:
            vals = named_poses_dict[pose_name]
            val_strs = [f"{v:.{precision}f}" for v in vals]
            lines.append(f"      {pose_name}: [{', '.join(val_strs)}]")

    # Append any other poses in dictionary not in ordering
    for pose_name, vals in named_poses_dict.items():
        if pose_name not in ordering:
            val_strs = [f"{v:.{precision}f}" for v in vals]
            lines.append(f"      {pose_name}: [{', '.join(val_strs)}]")

    # Append other existing parameters if present
    for k, v in params_dict.items():
        if k != "named_poses":
            extra_yaml = yaml.dump({k: v}, default_flow_style=False).strip()
            indented = "\n".join("    " + line for line in extra_yaml.splitlines())
            lines.append(indented)

    # Append any top-level keys outside manipulation_action_server
    for k, v in existing_data.items():
        if k != "manipulation_action_server":
            extra_yaml = yaml.dump({k: v}, default_flow_style=False).strip()
            lines.append("")
            lines.append(extra_yaml)

    lines.append("")
    return "\n".join(lines)


class ArmPoseCalibratorNode(Node):
    """Interactive Gamepad Calibration Node for Manipulator Landmark Poses."""

    def __init__(self) -> None:
        """Initialize parameters, subscribers, service, and state machine."""
        super().__init__("arm_pose_calibrator")

        # Declare and load parameters
        self._declare_and_load_parameters()

        # State storage
        self.current_step_idx: int = 0
        self.calibrated_poses: Dict[str, List[float]] = {}
        self.latest_joint_state: Optional[JointState] = None

        # Gamepad edge detection state
        self.prev_dpad_y: float = 0.0
        self.prev_menu_btn: int = 0

        # Subscriptions
        qos_joints = QoSProfile(
            history=HistoryPolicy.KEEP_LAST,
            depth=10,
            reliability=ReliabilityPolicy.BEST_EFFORT,
            durability=DurabilityPolicy.VOLATILE,
        )
        self.joint_sub = self.create_subscription(
            JointState, self.joint_states_topic, self.on_joint_state, qos_joints
        )

        qos_joy = QoSProfile(
            history=HistoryPolicy.KEEP_LAST,
            depth=10,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.VOLATILE,
        )
        self.joy_sub = self.create_subscription(
            Joy, self.joy_topic, self.on_joy, qos_joy
        )

        # Service for programmatic save
        self.save_srv = self.create_service(
            Trigger, "~/save_to_yaml", self.handle_save_service
        )

        self.get_logger().info(
            f"ArmPoseCalibratorNode initialized.\n"
            f"  - Target Pose Sequence: {self.target_poses}\n"
            f"  - Joints to record ({len(self.arm_joints)}): {self.arm_joints}\n"
            f"  - Output YAML: {self.output_yaml}\n"
            f"  - Controls:\n"
            f"      [D-Pad UP]   : Record current pose\n"
            f"      [D-Pad DOWN] : Undo/discard last recorded pose\n"
            f"      [MENU/START] : Save calibrated poses to YAML config"
        )
        self._print_current_prompt()

    def _declare_and_load_parameters(self) -> None:
        """Declare and load ROS parameters from external YAML or CLI overrides."""
        self.declare_parameter("target_poses", DEFAULT_TARGET_POSES)
        self.declare_parameter("arm_joints", DEFAULT_ARM_JOINTS)
        self.declare_parameter(
            "output_yaml",
            "/root/docker_ws/lekiwi_ros2/lekiwi_calibration/config/arm_named_poses.yaml",
        )
        self.declare_parameter("joint_states_topic", "/joint_states")
        self.declare_parameter("joy_topic", "/joy")
        self.declare_parameter("dpad_y_axis", 7)
        self.declare_parameter("menu_button", 7)
        self.declare_parameter("require_all_poses", True)
        self.declare_parameter("float_precision", 4)

        self.target_poses: List[str] = [
            str(p) for p in self.get_parameter("target_poses").value
        ]
        self.arm_joints: List[str] = [
            str(j) for j in self.get_parameter("arm_joints").value
        ]
        self.output_yaml: str = os.path.expanduser(
            str(self.get_parameter("output_yaml").value)
        )
        self.joint_states_topic: str = str(
            self.get_parameter("joint_states_topic").value
        )
        self.joy_topic: str = str(self.get_parameter("joy_topic").value)
        self.dpad_y_axis: int = int(self.get_parameter("dpad_y_axis").value)
        self.menu_button: int = int(self.get_parameter("menu_button").value)
        self.require_all_poses: bool = bool(
            self.get_parameter("require_all_poses").value
        )
        self.float_precision: int = int(
            self.get_parameter("float_precision").value
        )

    def _print_current_prompt(self) -> None:
        """Display guidance prompt for current active pose step."""
        if self.current_step_idx < len(self.target_poses):
            target = self.target_poses[self.current_step_idx]
            self.get_logger().info(
                f"\n>>> STEP [{self.current_step_idx + 1}/{len(self.target_poses)}]: "
                f"Position arm for '{target}'. Press D-Pad UP to record."
            )
        else:
            self.get_logger().info(
                f"\n>>> ALL {len(self.target_poses)} POSES RECORDED! "
                "Press MENU / START button (or call ~/save_to_yaml) to export to YAML."
            )

    def on_joint_state(self, msg: JointState) -> None:
        """Store incoming joint states."""
        self.latest_joint_state = msg

    def on_joy(self, msg: Joy) -> None:
        """Process gamepad input for recording, undoing, and saving poses."""
        dpad_y = (
            msg.axes[self.dpad_y_axis]
            if len(msg.axes) > self.dpad_y_axis
            else 0.0
        )
        menu_btn = (
            msg.buttons[self.menu_button]
            if len(msg.buttons) > self.menu_button
            else 0
        )

        # Edge detection: D-Pad UP (axis > 0.5) -> Record pose
        if dpad_y > 0.5 and self.prev_dpad_y <= 0.5:
            self.capture_active_pose()
        # Edge detection: D-Pad DOWN (axis < -0.5) -> Undo last pose
        elif dpad_y < -0.5 and self.prev_dpad_y >= -0.5:
            self.undo_last_pose()

        # Edge detection: MENU button pressed -> Save to YAML
        if menu_btn == 1 and self.prev_menu_btn == 0:
            self.save_poses_to_yaml()

        self.prev_dpad_y = dpad_y
        self.prev_menu_btn = menu_btn

    def capture_active_pose(self) -> None:
        """Record current arm joint positions for the current pose step."""
        if self.latest_joint_state is None:
            self.get_logger().warn(
                "Cannot record: No JointState received on topic "
                f"'{self.joint_states_topic}' yet."
            )
            return

        if self.current_step_idx >= len(self.target_poses):
            self.get_logger().warn(
                f"All {len(self.target_poses)} poses already captured. "
                "Press MENU / START button to save, or D-Pad DOWN to undo."
            )
            return

        target_name = self.target_poses[self.current_step_idx]

        try:
            positions = extract_joint_positions(
                self.latest_joint_state, self.arm_joints
            )
        except ValueError as err:
            self.get_logger().error(f"Failed to extract joint positions: {err}")
            return

        # Store captured pose
        self.calibrated_poses[target_name] = positions
        self.current_step_idx += 1

        formatted_vals = [f"{v:.{self.float_precision}f}" for v in positions]
        self.get_logger().info(
            f" [RECORDED {self.current_step_idx}/{len(self.target_poses)}] "
            f"Pose '{target_name}': [{', '.join(formatted_vals)}]"
        )

        self._print_current_prompt()

    def undo_last_pose(self) -> None:
        """Undo the most recent pose capture and step back."""
        if self.current_step_idx == 0:
            self.get_logger().warn("No recorded poses to undo. At initial step.")
            return

        self.current_step_idx -= 1
        target_name = self.target_poses[self.current_step_idx]
        if target_name in self.calibrated_poses:
            del self.calibrated_poses[target_name]

        self.get_logger().warn(
            f" [UNDO] Removed capture for '{target_name}'. "
            f"Now back at step [{self.current_step_idx + 1}/{len(self.target_poses)}]."
        )
        self._print_current_prompt()

    def save_poses_to_yaml(self) -> (bool, str):
        """Export recorded poses to target YAML configuration file."""
        if self.require_all_poses and len(self.calibrated_poses) < len(
            self.target_poses
        ):
            missing = [
                p for p in self.target_poses if p not in self.calibrated_poses
            ]
            msg = (
                f"Cannot save: Incomplete calibration. Missing poses: {missing}. "
                f"({len(self.calibrated_poses)}/{len(self.target_poses)} captured)"
            )
            self.get_logger().error(msg)
            return False, msg

        if not self.calibrated_poses:
            msg = "Cannot save: No poses have been recorded."
            self.get_logger().error(msg)
            return False, msg

        # Read existing YAML if file exists
        existing_data = {}
        if os.path.exists(self.output_yaml):
            try:
                with open(self.output_yaml, "r", encoding="utf-8") as f:
                    existing_data = yaml.safe_load(f) or {}
            except Exception as ex:
                self.get_logger().warn(
                    f"Could not parse existing YAML at {self.output_yaml}, generating new: {ex}"
                )
                existing_data = {}

        yaml_content = format_arm_poses_yaml(
            existing_data=existing_data,
            calibrated_poses=self.calibrated_poses,
            arm_joints=self.arm_joints,
            target_poses=self.target_poses,
            precision=self.float_precision,
        )

        # Ensure directory exists
        out_dir = os.path.dirname(os.path.abspath(self.output_yaml))
        os.makedirs(out_dir, exist_ok=True)

        try:
            with open(self.output_yaml, "w", encoding="utf-8") as f:
                f.write(yaml_content)

            msg = (
                f"Successfully exported {len(self.calibrated_poses)} poses "
                f"({list(self.calibrated_poses.keys())}) to {self.output_yaml}"
            )
            self.get_logger().info(
                f"\n========================================\n"
                f" [EXPORT SUCCESSFUL]\n{msg}\n"
                f"========================================"
            )
            return True, msg
        except Exception as ex:
            msg = f"Failed to write YAML to {self.output_yaml}: {ex}"
            self.get_logger().error(msg)
            return False, msg

    def handle_save_service(
        self, request: Trigger.Request, response: Trigger.Response
    ) -> Trigger.Response:
        """Trigger service callback to export YAML."""
        success, msg = self.save_poses_to_yaml()
        response.success = success
        response.message = msg
        return response


def main(args: Optional[List[str]] = None) -> None:
    """Initialize ROS context and spin ArmPoseCalibratorNode."""
    rclpy.init(args=args)
    node = ArmPoseCalibratorNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
